# Generated by Django 4.0.1 on 2022-01-25 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_barang', models.CharField(max_length=100)),
                ('isi_satuan', models.CharField(max_length=100)),
                ('jumlah_kemasan_satuan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NomorSkep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_sbp', models.CharField(max_length=100, unique=True)),
                ('tanggal_sbp', models.DateField(blank=True, null=True)),
                ('no_bdn', models.CharField(max_length=100, unique=True)),
                ('tanggal_bdn', models.DateField()),
                ('no_bmn', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tanggal_bmn', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merek', models.CharField(max_length=100)),
                ('isi', models.IntegerField()),
                ('jumlah_kemasan', models.IntegerField()),
                ('harga_jual_eceran', models.IntegerField()),
                ('nilai', models.IntegerField()),
                ('jenis_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kep.jenisbarang')),
                ('nomor_skep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kep.nomorskep')),
            ],
        ),
    ]
